### ISSUE TITLE
PBS selection statistic

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/sgkit#230] opened 2020-09-02 14:19 UTC
Implement the PBS statistic based on the version in [scikit-allel](
https://github.com/cggh/scikit-allel/blob/5f2f73ff926e105e5a65cacfc28f2928aba70f69/allel/stats/selection.py#L1262). This can be tested input data generated by msprime and comparing with scikit-allel's values.

Requires: #229, #225 

See also [notebook](https://github.com/pystatgen/sgkit-requirements/blob/master/stories/gwss-pbs/gwss-pbs.ipynb) from @alimanfoo.

**Comment by hammer** [comment] 2020-09-02 14:25
Dupe of #73?

**Comment by jeromekelleher** [comment] 2020-09-02 14:35
Yep, looks like it. I'll move the info in #73 here and close it, unless anyone disagrees?

**Closed** 2020-11-04 13:13 UTC
